---
title: "crop"
author: "steppe"
date: "`r Sys.Date()`"
output: html_document
---

Many of these datasets are very large we are going to crop them to the area of analysis, and save the subsets. 


```{r library}
library(sf)
library(terra)
library(tidyverse)
source('functions.R')
```

```{r define domain of data}

bound <- data.frame(
  y = c(30, 30, 50, 50, 30), 
  x = c(-85, -125, -125, -85, -85)
) %>% 
  st_as_sf(coords = c('x', 'y'), crs = 4326) %>% 
  st_bbox() %>% 
  st_as_sfc()

bb_vals <- c(-125, -85, 30, 50)
w_illi <- ext(bb_vals)

tile_cells <- st_make_grid(
  bound,
  what = "polygons", square = T, flat_topped = F, crs = 4326,
  n = c(
  abs(round( (bb_vals[2] - bb_vals[1]) / 5, 0)), # rows
    abs(round( (bb_vals[3] - bb_vals[4]) / 5, 0))) #cols
) %>% 
  st_as_sf() %>% 
  rename(geometry = x) %>% 
  mutate(x = st_coordinates(st_centroid(.))[,1],
         y = st_coordinates(st_centroid(.))[,2], 
         .before = geometry, 
         across(c('x', 'y'), round, 1),
         cellname = paste0('n', abs(y), 'w', abs(x))
         )

tile_cellsV <- vect(tile_cells)
```

```{r subset physical variables to domain, eval = F}

mason(dirin = '../geodata_raw/geomorphons/',
      dirout = '../geodata/geomorphons/',
      grid = tile_cellsV, fnames = 'cellname')

mason(dirin = '../geodata_raw/aspect/',
      dirout = '../geodata/aspect/',
      grid = tile_cellsV, fnames = 'cellname')

mason(dirin = '../geodata_raw/slope/',
      dirout = '../geodata/slope/',
      grid = tile_cellsV, fnames = 'cellname')
      
mason(dirin = '../geodata_raw/elevation/',
      dirout = '../geodata/elevation/',
      grid = tile_cellsV, fnames = 'cellname')

rm(mason)
```

```{r crop political boundary data to extent, eval = F}
counties <- st_read('../geodata_raw/USCounties/tl_2020_us_county.shp', quiet = T) %>% 
  st_transform(st_crs(tile_cells)) %>% 
  select(STATEFP, COUNTY = NAME)

states <- tigris::states() %>% 
  select(STATEFP, STATE = NAME, STUSPS) %>% 
  st_drop_geometry()

counties <- counties[st_intersects(counties, st_union(tile_cells)) %>% lengths > 0, ]
counties <- left_join(counties, states, by = "STATEFP") %>% 
  select(-STATEFP) %>% 
  arrange(STATE)

states <- counties %>%
  distinct(STUSPS) %>% 
  pull(STUSPS)

st_write(counties, dsn = file.path('../geodata/political', 'political.shp'))

rm(counties)
```

```{r crop mountain names database to extent, eval = F}

mtns <- st_read('../geodata_raw/globalMountains/GMBA_Inventory_v2.0_standard_basic.shp', 
        quiet = T) %>% 
  st_make_valid() %>% 
  select(MapName) %>% 
  st_crop(., st_union(tile_cells))

st_write(mtns, dsn = file.path('../geodata/mountains', 'mountains.shp'), quiet = T)

rm(mtns)
```

```{r crop geographic place name database to extent, eval = F}

files <- paste0('../geodata_raw/GNIS/Text/DomesticNames_', states, '.txt')
cols <- c('feature_name', 'prim_lat_dec', 'prim_long_dec')

places <- lapply(files, read.csv, sep = "|") %>% 
  map(., ~ .x |> select(all_of(cols))) %>% 
  data.table::rbindlist() %>% 
  st_as_sf(coords = c('prim_long_dec', 'prim_lat_dec'), crs = 4269) %>% 
  st_transform(4326)

places <- places[st_intersects(places, st_union(tile_cells)) %>% lengths > 0, ]

st_write(places, dsn = file.path('../geodata/places', 'places.shp'), quiet = T)

rm(places, cols, files)
```


```{r crop padus to domain, eval = F}

padus <- st_read(dsn = '../geodata_raw/PADUS3/PAD_US3_0.gdb', 
                 layer = 'PADUS3_0Fee') %>% 
  filter(State_Nm %in% states) %>% 
  select(Mang_Name, Unit_Nm) %>% 
  st_cast('MULTIPOLYGON')

tile_cells <- st_transform(tile_cells, st_crs(padus))
padus <- padus[st_intersects(padus, st_union(tile_cells)) %>% lengths > 0, ]
padus <- st_transform(padus, crs = 4326)

st_write(padus, dsn = file.path('../geodata/pad', 'pad.shp'), quiet = T)
rm(padus)
```

```{r geological map, eval = F}
geological <- st_read(
  '../geodata_raw/geologicalMap/USGS_StateGeologicMapCompilation_ver1.1.gdb', 
          layer = 'SGMC_Geology', quiet = T) %>% 
  select(GENERALIZED_LITH, UNIT_NAME) 

tile_cells <- st_transform(tile_cells, st_crs(geological))
geological <- geological[st_intersects(geological, st_union(tile_cells)) %>% lengths > 0, ]
geological <- st_crop(geological, st_union(tile_cells))
geological <- st_transform(geological, 4326)

st_write(geological, dsn = file.path('../geodata/geology', 'geology.shp'), quiet = T)

tile_cells <- st_transform(tile_cells, crs = 4326)
rm(geological)
```


```{r allotments, eval = F}

blm <- st_read(
  '../geodata_raw/BLMAllotments/BLM_Natl_Grazing_Allotment_Polygons.shp') %>% 
  select(ALLOT_NAME)
usfs <- st_read(
  '../geodata_raw/USFSAllotment/S_USA.Allotment.shp', quiet = T
) %>% 
  select(ALLOT_NAME = ALLOTMENT_) 

allotments <- bind_rows(blm, usfs) %>% 
  st_make_valid()
tile_cells <- st_transform(tile_cells, st_crs(allotments))
allotments <- allotments[st_intersects(allotments, st_union(tile_cells)) %>% lengths > 0, ]
allotments <- st_crop(allotments, st_union(tile_cells))
allotments <- st_transform(allotments, 4326)

st_write(allotments, dsn = file.path('../geodata/allotments', 'allotments.shp'), quiet = T)

rm(blm, usfs, allotments)
```

```{r public land survey system only for land west of CO border, eval = F}


bound_nm <- data.frame(
  y = c(31, 31, 50, 50, 31), 
  x = c(-95, -125, -125, -95, -95)
) %>% 
  st_as_sf(coords = c('x', 'y'), crs = 4326) %>% 
  st_bbox() %>% 
  st_as_sfc()

township <- st_read(
  '../geodata_raw/nationalPLSS/ilmocplss.gdb', layer = 'PLSSTownship', quiet = T
) %>% 
  st_cast('POLYGON') %>% 
  select(TWNSHPLAB, PLSSID)

bound_nm <- st_transform(bound_nm, st_crs(township))
township <- township[st_intersects(township, bound_nm) %>% lengths > 0, ]
township <- st_drop_geometry(township)

section <- st_read(
  '../geodata_raw/nationalPLSS/ilmocplss.gdb', layer = 'PLSSFirstDivision', quiet = T
) %>% 
  st_cast('POLYGON') %>% 
  select(FRSTDIVLAB, PLSSID, FRSTDIVID)

section <- section[st_intersects(section, bound_nm) %>% lengths > 0, ]

trs <- inner_join(section, township, 'PLSSID') %>% 
  mutate(TRS = paste(TWNSHPLAB, FRSTDIVLAB)) %>% 
  select(TRS)

before <- object.size(trs)
trs <- st_simplify(trs)
after <- object.size(trs)
object.size(trs)

st_write(trs, 
         dsn = file.path('../geodata/plss', 'plss.shp'), quiet = T)

rm(section, township, trs, bound_nm, before, after)
```

```{r modify names of variables to be in proper formats, eval = F}


sf::st_read('../geodata/political/political.shp', quiet = T) %>% 
  rename(County = COUNTY, State = STATE) %>% 
  st_write(., '../geodata/political/political.shp', quiet = T, append = F)

sf::st_read('../geodata/allotments/allotments.shp', quiet = T) %>% 
  dplyr::mutate(Allotment = str_to_title(ALLOT_NAME)) %>% 
  dplyr::select(-ALLOT_NAME) %>% 
  st_write(., '../geodata/allotments/allotments.shp', quiet = T, append = F)

sf::st_read('../geodata/plss/plss.shp', quiet = T) %>% 
  rename(trs = TRS) %>% 
  st_write(., '../geodata/plss/plss.shp', quiet = T, append = F)

sf::st_read('../geodata/pad/pad.shp', quiet = T) %>% 
  sf::st_make_valid() %>% 
  dplyr::filter(sf::st_is_valid(.)) %>% 
  mutate(Unit_Nm = str_replace(Unit_Nm, "National Forest", "NF"),
         Unit_Nm = str_replace(Unit_Nm, "Field Office", "FO"),
         Unit_Nm = str_replace(Unit_Nm, "National Wildlife Refuge", "NWR")) %>% 
  st_write(., '../geodata/pad/pad.shp', quiet = T, append = F)


sf::st_read('../geodata/places/places.shp', quiet = T) %>% 
  mutate(
    fetr_nm = str_remove(fetr_nm, ' Census Designated Place' ),
    fetr_nm = str_remove(fetr_nm, 'Township of '), 
    fetr_nm = str_remove(fetr_nm, ' \\(historical\\)'),
    fetr_nm = str_remove(fetr_nm, 'Village of '),
    fetr_nm = str_remove(fetr_nm, 'Town of '), 
    fetr_nm = str_remove(fetr_nm, 'City of ')
    ) %>% 
  filter(!str_detect(fetr_nm,
                     'Election Precinct| County|Ditch|Unorganized Territory|Canal|Lateral|Division|
                     River Division|Drain Number|Waste Pond|Commissioner District|Lake Superior|Lake Michigan')) %>% 
  st_write(., '../geodata/places/places.shp', quiet = T, append = F)


```


' Lake', ' lk.'
' Canyon', ' cnyn.'
' Campground', ' cmpgrnd.'
' Creek', ' crk.'
' River', ' rvr.'
' Reservoir', ' rsvr.'
' Fork', ' fk.'
' Number', ' #'
' Mountain', ' mtn.'
' Mountains', ' mtns.'
' Meadow', ' mdw.'
' Meadows' , ' mdws.'
' Point', ' pt.'

