---
title: "Barneby Lives usage example"
author: "steppe"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
library(tidyverse)
library(sf)
source('functions.R')
```


```{r dummy data}
dummy_pts <- data.frame(
  collectionNo = paste0(rep('RCB', 1000), seq(1:1000)),
  day = c(sample(1:31, size = 1000, replace = T)),
  month = c(sample(5:10, size = 1000, replace = T)),
  year = 2023,
  x = runif(1000, min = -120, max = -100), 
  y = runif(1000, min = 35, max = 48)
) %>% sf::st_as_sf(coords = c(x = 'x', y = 'y'), crs = 4326)

```


 first convert from american date format (m%d%year%) to ISO 8601 for both collection and determination date 

 second from ISO 8601 prepare notation dates for day of collection and date of determination in text format



```{r Date parsing}


#' create herbarium format dates for specimens
#' 
#' this function will return up to two additional columns with x. 'coll_date_text' a text format for the date of collection and 'det_date_text" a shorter text format date for identification
#' @param x an (sf/tibble/) data frame with both the collection date
#' and determination date
#' @param coll_date date of collection, expected to be of the format 'MM/DD/YYYY', minor checks for compliance to the format will be carried out before returning an error.
#' @param det_date date of determination, same format and processes as above. 
#' @returns coll_date ISO 8601, det_date ISO 8601, month, day, year, coll_date_text, det_date_text columns for printing onto the label
date_parser <- function(x, coll_date, det_date){
  
  coll_date_q <- enquo(coll_date)
  det_date_q <- enquo(det_date)
  
  names_v <- c('_dmy', '_day', '_mo',  '_yr', '_text')
  column_names <- c(paste0(coll_date, names_v), paste0(det_date, names_v) )
  
  mdy2dmy <- function(x){format(as.Date(x, format = "%m/%d/%Y"), "%d/%m/%Y")}
  
   x_dmy <- x |> 
    mutate(across(.cols = c(!!coll_date_q, !!det_date_q), lubridate::mdy, .names = "{.col}_dmy")) |>
    mutate(across(ends_with('_dmy'), ~ lubridate::month(.), .names = "{.col}_mo"),
           across(ends_with('_dmy'), ~ lubridate::day(.), .names = "{.col}_day"),
           across(ends_with('_dmy'), ~ lubridate::year(.), .names = "{.col}_yr")) |>
    mutate(across(.cols = c(!!coll_date_q, !!det_date_q), date2text, .names = '{.col}_text')) |>
    rename_with( ~ stringr::str_remove(., '_dmy'), matches("_dmy_.*$")) |>
    relocate(any_of(column_names), .before = last_col())
  
  return(x_dmy)
}

```

```{r}

fourtet <- data.frame(col_date = c('12/23/2003','07/09/2023', '1/13/2016'),
                      det_date = c('12/25/2003','07/09/2023', '1/13/2016'),
                      tet = c('abc', 'def', 'ggg'))

date_parser(fourtet, coll_date = 'col_date', det_date = 'det_date')

```




```{r Acquire administrative geodata}

places <- sf::st_read('../geodata/places/places.shp', quiet = T)

out1 <- political_grabber(dummy_pts, 'collectionNo')
out2 <- place_grabber(dummy_pts)
out3 <- physical_grabber(dummy_pts)


browseVignettes("ggtree")
```

