---
title: "Barneby Lives!"
author: "steppe"
date: "9/13/2021"
output: html_document
---

```{r}
library(tidyverse)
library(kewr)
library(WorldFlora)
WFO.remember()
```


stages...
verify the spelling of the genus (parse these from the POWO webshot)
verify the spelling of the epithet (parse these from the POWO webshot)

if not verified
fuzzy match genus... (somehow get a local list.....)
fuzzy match epithet...

find authorship...


```{r}
x <- search_powo("Ivesia lycopodioides")
# some considerations.... 

# If the species cannot be found, RESULTS will be NULL 
re_none <- search_powo("Ivesia lycopodioides var. lycopodioides")

try_again <- 



is.null(re_none[["results"]]){
  
  try_again
  
} else {final <- result_grabber(query_results)} 

# if results are NULL, can we strip from subsp./var./ssp. until the end to query only species?

# in the situation where there is a synonym of the group RESULTS will be a list of length two. 
re_syn <- search_powo("Ivesia lycopodioides")
# results will be a list of length 2

# when the appropriate name is searched RESULTS will be a list of length one...
re_perf <- search_powo("Potentilla lycopodioides")




# once everything has gone correctly - i.e. we have found the species, we come to
# this stage of the process where we extract the values. 

result_grabber <- function(x){

  # subset the appropriate data frame, there is one if clean data were entered, 
  # and two if a synonym was entered.
  results <- x[['results']]
  resultT <- data.frame(results[which(lapply(results, length) == 8)])

  # the main variables which all results should have. 
  family = resultT$family
  authority = resultT$author
  full_name = resultT$name
  split_name <- unlist(str_split(full_name, pattern = " "))
  genus = split_name[1]
  epithet = split_name[2]

  # the infra species information if relevant. 
  if( length(split_name) > 2){
     infraspecies = split_name[length(split_name)]
  } else {infraspecies = NA}

  if( length(split_name) > 2){
     infrarank = str_extract(full_name, ' var\\. | spp\\. | subsp\\. ') |>
       str_trim(side = 'both')
  } else {infrarank = NA}
  
  taxonomic_info <- data.frame(
    family, name_authority = paste(full_name, authority), 
    full_name, genus, epithet, infrarank, infraspecies, authority
  )
  
  return(taxonomic_info)
}

result_grabber(re_syn)

```



```{r}

test <- WorldFlora::WFO.match(
  spec.data = WFO.example, 
   spec.name = 'binomial',
   Fuzzy = 0.1)

family_spellings <- vascular.families %>% 
  dplyr::pull(Family)


pec.test <- data.frame(spec.name=c("Faidherbia albida", "Acacia albida",
"Faidherbia albidum", "Faidherbia albidus",
"Faidherbia albiida",
"Prunus africanus", "Prunos africanea",
"Prunus afrocaneus", "Prunus afrocaneos"))

match1 <- WFO.match.fuzzyjoin(spec.data=spec.test, WFO.data=WFO.example,
fuzzydist.max = 6)
```

   
